project:
  type: website
  output-dir: docs

website:
  title: "On Taking Notes"
  search:
    type: textbox
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/recleev
      - icon: linkedin
        href: https://www.linkedin.com/in/recleev/
format:
  html:
    metadata:
      license: "CC BY 4.0"
    theme:
      - sketchy
      - styles.scss
brand: on-taking-notes.yml
page-layout: full
