project:
  type: website
  output-dir: docs

website:
  title: "On Taking Notes"
  site-url: https://recleev.github.io/on-taking-notes/
  description: "Recle's blog about taking handwritten notes"
  favicon: logo/on-taking-notes.png
  search:
    type: textbox
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/recleev
      - icon: linkedin
        href: https://www.linkedin.com/in/recleev/
      - icon: cup-hot-fill
        href: https://buymeacoffee.com/recleev
format:
  html:
    metadata:
      license: "CC BY 4.0"
    theme:
      - sketchy
      - styles.scss
brand: on-taking-notes.yml
page-layout: full
