project:
  type: website

website:
  title: "On Taking Notes"
  search:
    type: textbox
  navbar:
    right:
      - icon: github
        href: https://github.com/recleev
      - icon: linkedin
        href: https://www.linkedin.com/in/recleev/
format:
  html:
    theme:
      - sketchy
      - styles.scss
brand: monochrome.yml
page-layout: full
